### ISSUE TITLE
Failure to render HOST environment variable

### ISSUE THREAD

**Issue by pitbuster** [guangie88/tera-cli#32]
When running `tera -s "{{ HOST }}" --env` I get the following error:
```
Tera application error: Failed to render '__tera_one_off'
```

Other variables seem to work fine
```
$ tera -s "{{ EDITOR }}" --env
nvim%
```

**Comment by alerque** [comment]
Try `env | grep HOST`. I'd be willing to bet you don't actually have an environment variable called `HOST` even set. There is a better chance you'll have `HOSTNAME`.

**Comment by pitbuster** [comment]
@alerque today I learned that `HOST` (in zsh) and `HOSTNAME` (in bash) are handled in a special way, so they won't show up in `env` output, but are still accessible in the shell (i.e. `echo $HOST` or `echo $HOSTNAME`, depending on your shell, will work). I am closing since I got a workaround: `HOST=$HOST tera -s "{{ HOST }}" --env`.

**Comment by alerque** [comment]
They are not so very special, they are just marked as local variables. You can tell the shell to export them such that child processes can read them (i.e. make them show up in the environment:

```zsh
export HOST
```

```bash
export HOSTNAME
```

Your syntax is just setting an environment variable of the same name from the local variable and using it just for the scope of one child process. You can chose to export the variable in an earlier shell command or even in your shell's init configuration.
